'''
    Problem 002: 
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''

sumValues = 2;
fibonacciValues = [1,2];
i = 1

while fibonacciValues[i] < 4_000_000:
    value01 = fibonacciValues[i]
    value02 = fibonacciValues[i-1]
    newFibonacciValue = value01 + value02
    i = i + 1
    fibonacciValues.append(newFibonacciValue)
    if newFibonacciValue%2 == 0:
        sumValues += newFibonacciValue

print(sumValues)
